
baseURL = "https://ixiaopan.github.io/blog/"
# title = "Hugo Themes"
theme = "harbor"
paginate = 8
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir = "docs"
googleAnalytics = "UA-203640627-1"

[taxonomies]
  # Use singular rather than plural for default taxonomies
  tag = "tags"
  category = "categories"

[params]
  customCSS = ["css/main.css"]


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Author]
  name = "ixiaopan"




# [permalinks]
# 	post = "/:year/:month/:day/:filename/"
# 	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]


[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "about"
  weight = 3

# [[params.nav]]
#   identifier = "tags"
#   name = "Tags"
#   icon = "fas fa-tag fa-lg"
#   url = "tags"
#   weight = 3

[[params.nav]]
  identifier = "categories"
  name = "Category"
  icon = "fas fa-folder-open fa-lg"
  url = "categories"
  weight = 3


# copy paste this block and change for each social media to add how many ever social media
# acounts/links you want, add icon from https://fontawesome.com/
[[params.social]]
  name= "Email"
  url="mailto:?to=xiaopan.wpp@outlook.com"
  icon="fas fa-envelope"

[[params.social]]
  name= "GitHub"
  url="https://github.com/ixiaopan"
  icon="fab fa-github"

[[params.social]]
  name= "Linkedin"
  url="https://www.linkedin.com/in/ixiaopan"
  icon="fab fa-linkedin"


[[params.social]]
  name= "Bilibili"
  url="https://space.bilibili.com/22910840"
  icon="fab fa-youtube"

[params.logo]
  url = "me.JPG" # static/images/icon.JPG
  width = 50
  height = 50
  alt = "Logo"
